### PR TITLE
Added a download status

### PR DESCRIPTION
**Pull request by schtobia**
This MR would a download status for and a more comprehensive compare against a given checksum for CPM.

Additionally, the versions of the pulled libraries is bumped.

### CODE REVIEW

**Review by TheLartians — APPROVED** [review]
Thanks for the PR, the status and checksum checks are definitely a welcome improvement!
Unfortunately they would need to be updated for each new version of CPM.cmake. It actually would be awesome to update the "official" [`get_cpm.cmake` script](https://github.com/cpm-cmake/CPM.cmake/blob/master/cmake/get_cpm.cmake) (with values filled in in the [publish GitHub workflow](https://github.com/cpm-cmake/CPM.cmake/blob/master/.github/workflows/publish.yaml)) to include the checksum as well!

**Comment by TheLartians** [comment]
@schtobia the code style status check is failing. Could you run the [code formatter](https://github.com/TheLartians/ModernCppStarter#run-clang-format) and update the PR?

**Comment by schtobia** [comment]
> It actually would be awesome to update the "official" [`get_cpm.cmake` script](https://github.com/cpm-cmake/CPM.cmake/blob/master/cmake/get_cpm.cmake) (with values filled in in the [publish GitHub workflow](https://github.com/cpm-cmake/CPM.cmake/blob/master/.github/workflows/publish.yaml)) to include the checksum as well!

You're absolutely right. I will work on this, but have no ETA.

**Review by TheLartians — APPROVED** [review]
I've gone ahead and updated to the new `get_cpm.cmake` script from the CPM project. Thanks again for the PR in both projects!

**Pull request merged**
